package org.divyansh.components;

public  enum SpecialKeyValues {
    BACKSPACE,
    CLEAR_ALL,
    EQUAL_TO,
    PI,
    E, BRACKETCLOSE, BRACKETOPEN, SQUARE_BRACKETOPEN, SQUARE_BRACKETCLOSE, SQUARE_CURLYBRACKETCLOSE, SQUARE_CURLYBRACKETOPEN, DOT
}
